name: Release
on:
push:
tags:
- 'v*'
jobs:
package:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Create tar.zst
run: |
tar -c --exclude='.git' project-helix | zstd -o project-helix-${{ github.ref_name }}.tar.zst
- name: Upload artifact
uses: actions/upload-artifact@v4
with:
name: project-helix-${{ github.ref_name }}.tar.zst
path: project-helix-${{ github.ref_name }}.tar.zst
